// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See the LICENSE file in the project root for full license information.

package com.microsoft.store.samples.partnerconsent.models;

import java.util.Date;

public class StateData
{
    /**
     * The expiration time for the state data.
     */
    private Date expirationDate;

    /**
     * The value included in the request, generated by the app, that is included in the resulting id_token as a claim.
     */
    private String nonce; 

    /**
     * Initializes a new instance of the {@link StateData} class
     * 
     * @param nonce The value included in the request, generated by the app, that is included in the resulting id_token as a claim.
     * @param expirationDate The expiration time for the state data.
     */
    public StateData(String nonce, Date expirationDate)
    {
        this.expirationDate = expirationDate; 
        this.nonce = nonce; 
    }

    /**
     * Gets the expiration time for the state data.
     * 
     * @return The expiration time for the state data.
     */
    public Date getExpirationDate() {
        return expirationDate;
    }
    
    /**
     * Gets the value included in the request, generated by the app, that is included in the resulting id_token as a claim.
     * 
     * @return The value included in the request, generated by the app, that is included in the resulting id_token as a claim.
     */
    public String getNonce() {
        return nonce;
    }
}